### ISSUE TITLE
Enumerable.All Method

### ISSUE THREAD

**Issue by the-pat** [ShittyLabs/shitty_linq_ex#2]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.all

**Comment by amycruz97** [comment]
please can you elaborate more on the issue

**Comment by the-pat** [comment]
@amycruz97, apologies. There are many methods to implement and creating the issues takes time. 😅 

From the docs:
> Determines whether all elements of a sequence satisfy a condition.

Check out the [`where` method](https://github.com/ShittyLabs/shitty_linq_ex/blob/master/lib/shitty_linq_ex.ex#L21) as an example.

**Comment by chr1sto** [comment]
Gonna take that one.

**Comment by the-pat** [comment]
You got it! Happy hacking 🎃
