### ISSUE TITLE
Enumerable.TakeLast Method

### ISSUE THREAD

**Issue by the-pat** [ShittyLabs/shitty_linq_ex#45]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.takelast?view=netcore-3.1

**Comment by volcov** [comment]
if I did the take and the reverse, I think it seems fair to do the takeLast HAHAHAHA! xD

**Comment by the-pat** [comment]
It's only fair 🤣

Happy hacking 🎃
